services:
  - name: node-render-app
    type: web
    env: node
    plan: free
    buildCommand: yarn install --production
    startCommand: node index.js
    envVars:
      - key: APP_NAME
        sync: false
